#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'nav2-gazebo-spawner','console_scripts','nav2_gazebo_spawner'
__requires__ = 'nav2-gazebo-spawner'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('nav2-gazebo-spawner', 'console_scripts', 'nav2_gazebo_spawner')()
    )
